import json
from pathlib import Path
from typing import Any

import streamlit as st

from idms_modernizer.parsers.cobol_pdf_extractor import CobolPdfExtractor
from idms_modernizer.services.phase2_conversion_bridge import (
    Phase2ConversionBridge
)

try:
    from idms_db2_converter.exceptions import ConversionError
except Exception:
    class ConversionError(Exception):
        pass


class Phase2ConverterPanel:
    """
    Streamlit panel for running Phase 2 conversion inside Phase 1 app.

    Inputs:
    - COBOL text, COBOL PDF, or COBOL text file
    - Canonical JSON generated by Phase 1
    - Phase 2 metadata JSON generated by Phase 1
    - DB2 DDL generated by Phase 1
    - Optional IDMS schema text
    - Optional relationship overrides

    Important:
    - No hardcoded relationship overrides.
    - Relationship override JSON is dynamically generated from Phase 2 metadata
      when the user chooses to use overrides.
    """

    def render(
        self,
        canonical_json: str,
        phase2_metadata_json: str,
        ddl_text: str,
        idms_schema_text: str | None = None
    ) -> None:

        st.header(
            "Phase 2 - IDMS Retrieval COBOL to DB2 COBOL"
        )

        st.markdown(
            """
Use this section to convert an IDMS retrieval COBOL program into DB2 embedded SQL COBOL using the Phase 1 outputs generated above.
"""
        )

        with st.expander(
            "Phase 1 Inputs Passed to Phase 2",
            expanded=False
        ):
            st.subheader(
                "Canonical JSON"
            )

            st.code(
                canonical_json or "",
                language="json"
            )

            st.subheader(
                "Phase 2 Metadata JSON"
            )

            st.code(
                phase2_metadata_json or "",
                language="json"
            )

            st.subheader(
                "DB2 DDL"
            )

            st.code(
                ddl_text or "",
                language="sql"
            )

        st.subheader(
            "COBOL Input"
        )

        cobol_text = self._render_cobol_input()

        st.subheader(
            "Conversion Settings"
        )

        target_program = st.text_input(
            "Target PROGRAM-ID",
            value="",
            placeholder="Example: DEPTDB2"
        )

        col1, col2, col3 = st.columns(3)

        with col1:
            use_ddl = st.checkbox(
                "Use DB2 DDL",
                value=True,
                help="Recommended. DDL should be the physical source of truth."
            )

        with col2:
            use_phase2_metadata = st.checkbox(
                "Use Phase 2 Metadata",
                value=True,
                help="Recommended. Uses Phase 1 generated mapping metadata."
            )

        with col3:
            use_idms_schema = st.checkbox(
                "Use IDMS Schema Text",
                value=False,
                help="Optional. Usually not required if canonical, DDL, and Phase 2 metadata are provided."
            )

        use_overrides = st.checkbox(
            "Use relationship key overrides",
            value=False,
            help="Optional. Dynamically generated from Phase 2 metadata when enabled."
        )

        relationship_overrides_json = ""

        if use_overrides:
            relationship_overrides_json = self._render_relationship_overrides(
                phase2_metadata_json=phase2_metadata_json
            )

        phase2_idms_schema_text = ""

        if use_idms_schema:
            phase2_idms_schema_text = st.text_area(
                "Paste IDMS schema/subschema listing text",
                height=300,
                value=idms_schema_text or ""
            )

        convert_clicked = st.button(
            "Convert to DB2 COBOL",
            type="primary"
        )

        if convert_clicked:
            self._run_conversion(
                cobol_text=cobol_text,
                canonical_json=canonical_json,
                phase2_metadata_json=(
                    phase2_metadata_json
                    if use_phase2_metadata
                    else ""
                ),
                ddl_text=(
                    ddl_text
                    if use_ddl
                    else ""
                ),
                idms_schema_text=(
                    phase2_idms_schema_text
                    if use_idms_schema
                    else None
                ),
                relationship_overrides_json=(
                    relationship_overrides_json
                    if use_overrides
                    else None
                ),
                target_program=target_program,
                use_ddl=use_ddl,
                use_idms_schema=use_idms_schema,
                use_overrides=use_overrides
            )

    def _render_cobol_input(
        self
    ) -> str:

        input_mode = st.radio(
            "Choose COBOL input method",
            [
                "Paste COBOL",
                "Upload COBOL PDF",
                "Upload COBOL Text File"
            ],
            horizontal=True
        )

        cobol_text = ""

        if input_mode == "Paste COBOL":
            cobol_text = st.text_area(
                "Paste IDMS COBOL retrieval program",
                height=420,
                placeholder="Paste DEPTRPT or another IDMS retrieval program here..."
            )

        elif input_mode == "Upload COBOL PDF":
            cobol_text = self._load_cobol_from_pdf()

        elif input_mode == "Upload COBOL Text File":
            cobol_text = self._load_cobol_from_text_file()

        return cobol_text

    def _load_cobol_from_pdf(
        self
    ) -> str:

        cobol_text = ""

        cobol_pdf = st.file_uploader(
            "Upload COBOL PDF",
            type=[
                "pdf"
            ],
            key="phase2_cobol_pdf"
        )

        if cobol_pdf is None:
            return cobol_text

        temp_path = self._save_uploaded_file(
            uploaded_file=cobol_pdf,
            folder="data/temp"
        )

        extractor = CobolPdfExtractor()

        try:
            cobol_text = extractor.extract_text(
                temp_path
            )

            st.success(
                "COBOL PDF extracted successfully."
            )

            cobol_text = st.text_area(
                "Extracted COBOL text",
                value=cobol_text,
                height=420
            )

        except Exception as ex:
            st.error(
                f"Failed to extract COBOL PDF: {ex}"
            )

        return cobol_text

    def _load_cobol_from_text_file(
        self
    ) -> str:

        cobol_text = ""

        cobol_file = st.file_uploader(
            "Upload COBOL source file",
            type=[
                "cbl",
                "cob",
                "txt"
            ],
            key="phase2_cobol_text"
        )

        if cobol_file is None:
            return cobol_text

        try:
            cobol_text = cobol_file.read().decode(
                "utf-8",
                errors="ignore"
            )

            st.success(
                "COBOL text file loaded successfully."
            )

            cobol_text = st.text_area(
                "Loaded COBOL text",
                value=cobol_text,
                height=420
            )

        except Exception as ex:
            st.error(
                f"Failed to read COBOL file: {ex}"
            )

        return cobol_text

    def _render_relationship_overrides(
        self,
        phase2_metadata_json: str
    ) -> str:

        st.markdown(
            """
Relationship overrides are generated from the current Phase 2 metadata.  
You can edit them before conversion if needed.
"""
        )

        generated_overrides = self._build_overrides_from_phase2_metadata(
            phase2_metadata_json
        )

        if not generated_overrides:
            st.info(
                "No complete relationship overrides could be generated from Phase 2 metadata."
            )

            generated_overrides = {
                "relationships": []
            }

        return st.text_area(
            "Relationship key overrides JSON",
            height=300,
            value=json.dumps(
                generated_overrides,
                indent=2
            )
        )

    def _build_overrides_from_phase2_metadata(
        self,
        phase2_metadata_json: str
    ) -> dict[str, Any]:

        if not phase2_metadata_json or not phase2_metadata_json.strip():
            return {
                "relationships": []
            }

        try:
            payload = json.loads(
                phase2_metadata_json
            )

        except json.JSONDecodeError:
            return {
                "relationships": []
            }

        relationships = payload.get(
            "relationships",
            []
        )

        override_relationships = []

        for relationship in relationships:
            set_name = self._get_first_non_empty(
                relationship,
                [
                    "set_name",
                    "name",
                    "relationship"
                ]
            )

            parent_record = self._get_first_non_empty(
                relationship,
                [
                    "parent_record",
                    "parent_table"
                ]
            )

            child_record = self._get_first_non_empty(
                relationship,
                [
                    "child_record",
                    "child_table"
                ]
            )

            parent_key = self._get_first_non_empty(
                relationship,
                [
                    "parent_key",
                    "parent_pk"
                ]
            )

            child_fk = self._get_first_non_empty(
                relationship,
                [
                    "child_fk",
                    "foreign_key"
                ]
            )

            order_by = relationship.get(
                "order_by",
                []
            )

            if not set_name:
                continue

            if not parent_record:
                continue

            if not child_record:
                continue

            item = {
                "set_name": self._to_idms_name(set_name),
                "parent_record": self._normalize_name(parent_record),
                "child_record": self._normalize_name(child_record)
            }

            if parent_key:
                item[
                    "parent_key"
                ] = self._normalize_name(parent_key)

            if child_fk:
                item[
                    "child_fk"
                ] = self._normalize_name(child_fk)

            if order_by:
                item[
                    "order_by"
                ] = [
                    self._normalize_name(value)
                    for value in order_by
                    if value
                ]

            override_relationships.append(
                item
            )

        return {
            "relationships": override_relationships
        }

    def _run_conversion(
        self,
        cobol_text: str,
        canonical_json: str,
        phase2_metadata_json: str,
        ddl_text: str,
        idms_schema_text: str | None,
        relationship_overrides_json: str | None,
        target_program: str | None,
        use_ddl: bool,
        use_idms_schema: bool,
        use_overrides: bool
    ) -> None:

        if not cobol_text or not cobol_text.strip():
            st.error(
                "COBOL code is required."
            )
            st.stop()

        bridge = Phase2ConversionBridge()

        try:
            converted, validation_messages = bridge.convert(
                cobol_text=cobol_text,
                canonical_json=canonical_json,
                phase2_metadata_json=phase2_metadata_json,
                ddl_text=ddl_text,
                idms_schema_text=idms_schema_text,
                relationship_overrides_json=relationship_overrides_json,
                target_program=target_program,
                use_ddl=use_ddl,
                use_idms_schema=use_idms_schema,
                use_overrides=use_overrides
            )

            st.success(
                "Phase 2 conversion completed."
            )

            if validation_messages:
                st.warning(
                    "Conversion completed with validation messages."
                )

                for message in validation_messages:
                    st.write(
                        f"- {message}"
                    )

            else:
                st.info(
                    "Validation passed."
                )

            st.subheader(
                "Final DB2 COBOL"
            )

            st.text_area(
                "Copy converted DB2 COBOL",
                value=converted,
                height=700
            )

        except ConversionError as exc:
            st.error(
                "Phase 2 conversion failed."
            )

            st.code(
                str(exc),
                language="text"
            )

        except Exception as exc:
            st.error(
                "Unexpected Phase 2 conversion error."
            )

            st.code(
                str(exc),
                language="text"
            )

    def _save_uploaded_file(
        self,
        uploaded_file,
        folder: str
    ) -> str:

        target_folder = Path(
            folder
        )

        target_folder.mkdir(
            parents=True,
            exist_ok=True
        )

        target_path = (
            target_folder
            / uploaded_file.name
        )

        with open(
            target_path,
            "wb"
        ) as file:
            file.write(
                uploaded_file.getbuffer()
            )

        return str(
            target_path
        )

    def _get_first_non_empty(
        self,
        source: dict[str, Any],
        keys: list[str]
    ) -> str | None:

        for key in keys:
            value = source.get(
                key
            )

            if value is None:
                continue

            value = str(
                value
            ).strip()

            if value:
                return value

        return None

    def _normalize_name(
        self,
        value: str | None
    ) -> str:

        if value is None:
            return ""

        return str(
            value
        ).strip().upper().replace(
            "-",
            "_"
        )

    def _to_idms_name(
        self,
        value: str | None
    ) -> str:

        if value is None:
            return ""

        return str(
            value
        ).strip().upper().replace(
            "_",
            "-"
        )